name: Build & Deploy site

on:
  push:
    branches: [ "main" ]
    paths:
      - "events.xlsx"
      - "build.py"
      - ".github/workflows/deploy.yml"
      - "docs/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests

      - name: Build data
        env:
          EXCEL_PATH: events.xlsx
          # Set this to an email you control to comply with Nominatim usage guidelines
          NOMINATIM_USER_AGENT: "reballot-events-map/1.0 (contact: your.email@example.com)"
        run: |
          python build.py

      - name: Commit built data (if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/data/events.json .geocode_cache.json || true
          git commit -m "Build data for site" || echo "No changes to commit"
          git push
